#version 450

layout(local_size_x = 256) in;

layout(set = 0, binding = 0, std430) buffer OutputBuffer { float output_data[]; };
layout(set = 0, binding = 1, std430) readonly buffer AddBuffer { float add_data[]; };

layout(push_constant) uniform Push { uint p[1]; } pc;

void main() {
    uint index = gl_GlobalInvocationID.x;
    if (index >= pc.p[0]) return;
    output_data[index] += add_data[index];
}
